name: Cypress Tests
on: 
  #push:
   schedule:
   - cron: "0 0 * * *" 
jobs:
  cypress-run:
    runs-on: windows-latest
    environment: 
      name: india
 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Install Chrome
      #   run: sudo apt-get install -y google-chrome-stable
      
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          record: true
          parallel: true
          browser: chrome
          headless: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_location: india
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_location: india
