name: Cypress Tests

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser to run tests (chrome, firefox, edge)'
        required: false
        default: 'chrome'
      headless:
        description: 'Run tests in headless mode (true/false)'
        required: false
        default: 'true'
      retries:
        description: 'Number of retries on test failure'
        required: false
        default: '2'

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Chrome
        run: sudo apt-get install -y google-chrome-stable

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          record: true
          parallel: true
          browser: ${{ github.event.inputs.browser }}
          headless: ${{ github.event.inputs.headless }}
          config: retriesRunMode=${{ github.event.inputs.retries }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
